block.block.*.third_party.block_cache:
  type: mapping
  label: Block cache third party settings
  mapping:
    disable:
      type: boolean
      label: Disable cache
    force_disable:
      type: boolean
      label: Force disable
    miliseconds:
      type: integer
      label: Timeout miliseconds
